 
### Login with Basic User
# @name loginUser
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}  

# Variables de entorno
@baseUrl = http://localhost:8082
@authToken = Bearer {{ loginUser.response.body.accessToken }}

### Obtener lista de servicios
# @name getServices

GET {{baseUrl}}/api/services
Content-Type: application/json
Authorization: {{ authToken }}

###
POST {{baseUrl}}/api/services/4f83b8e6-86a8-4ee7-ac5a-bb5febaa978f/comments
Content-Type: application/json
Authorization: {{ authToken }}

{
  "serviceId": "4f83b8e6-86a8-4ee7-ac5a-bb5febaa978f",
  "profileId": 1,
  "rating": 5.0,
  "content": "Me encanta este lugar, la comida es deliciosa y el ambiente es acogedor."
}

###

GET {{baseUrl}}/api/comments/service-id/1898194223
Content-Type: application/json
Authorization: {{ authToken }}

###






